<div id="menu">
    <ul>
        <!INDIETRO>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'reservedarea',
                                        ), 
                                        'default',true);?>" title="Torna alla home di area riservata">Indietro	</a></p>
        </li>
        <!Aggiungi Categoria>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'newcategoria',
                                        ), 
                                        'default',true);?>" title="Aggiungi una nuova Categoria">Aggiungi Categoria	</a></p>
        </li>
        <!Elimina Categoria>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'deletecategoria',
                                        ), 
                                        'default',true);?>" title="Elimina una Categoria">Elimina Categoria	</a></p>
        </li>

        <!Modifica Categoria>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'updatecategoria',
                                        ), 
                                        'default',true);?>" title="Modifica una Categoria">Modifica Categoria	</a></p>
        </li>


    </ul>
</div>