<div id="menu">
    <ul>
        <!HOME>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'index',
                                        ), 
                                        'default',true);?>" title="Home">Home	</a></p>
        </li>
        <!AZIENDE>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'aziende',                                    
                                        ), 
                                        'default',true);?>" title="Aziende">Aziende	</a></p>
        </li>
        <!CHI SIAMO>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                            'controller' => 'public',
                            'action'     => 'viewstatic',
                            'staticPage' => 'who'), 
                            'default',true
                            ); ?>" title="Chi Siamo">Chi Siamo	</a></p>
        </li>
        <!DOVE SIAMO>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                            'controller' => 'public',
                            'action'     => 'viewstatic',
                            'staticPage' => 'where'), 
                            'default',true
                            ); ?>" title="Dove Siamo">Dove Trovarci	</a></p>
        </li>
        <!CONTATTACI>
        <li>
            <p class="p_menu"><a href="mailto:s1071182@studenti.univpm.it" title="Contatti">Contattaci</a></p>
        </li>
         <!FAQ>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'faq',                                    
                                        ), 
                                        'default',true);?>" title="FAQ">FAQ		</a></p>
        </li>   
        
         <!PROFILO>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'modificaprofilo',                                    
                                        ), 
                                        'default',true);?>" title="Modifica il tuo Profilo">Il tuo Profilo		</a></p>
        </li>
        
        <!LOGOUT>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'logout',                                    
                                        ), 
                                        'default',true);?>" title="Fai il logout">Logout		</a></p>
        </li>
    </ul>
</div>