<div id="menu">
    <ul>
        <!INDIETRO>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'reservedarea',
                                        ), 
                                        'default',true);?>" title="Torna alla home di area riservata">Indietro	</a></p>
        </li>
        <!Aggiungi Azienda>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'newazienda',
                                        ), 
                                        'default',true);?>" title="Aggiungi una nuova Azienda">Aggiungi Azienda	</a></p>
        </li>
        <!Elimina Azienda>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'deleteazienda',
                                        ), 
                                        'default',true);?>" title="Elimina una Azienda">Elimina Azienda	</a></p>
        </li>

        <!Modifica Azienda>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'updateazienda',
                                        ), 
                                        'default',true);?>" title="Modifica una Azienda">Modifica Azienda	</a></p>
        </li>


    </ul>
</div>