<div id="header">   <!l'header contiene i div del logo e della barra di ricerca>
    <div id="logo"> <!contiene il link all'immagine>
        <a href="<?= $this->url(array(          //questo riferimento permmette facendo click sull'immagine
            'controller' => 'public',       //di ricaricare la pagina inziale, avviando il la indexAction
            'action'     => 'index',        //del PublicController
            ), 
            'default',true);?>"> 
            <img id="img_logo" src=<?= $this->logo ?>><!riferimento alla posizione dell'immagine (da sistemare)>
        </a>
	
    </div>
                      
    <div id="div_src" ><!questo div contiene la form di inserimento e i bottoni di login e registrazione>
				
        <form class="src" id="form_src" name="search" action="" method="post">
						
            <select id="cat_src" name="cat"> 
                <option id="opt_src">Tutte le categorie</option>
                <option id="opt_src">cat1</option>
                <option id="opt_src">cat2</option>
            </select>		

            <input id="desc_src" name="desc" type="text" placeholder="Cerca"> 

            <input id="submit_src" type="submit" value="Cerca">
									
        </form>
    </div>
</div>