<div id="menu">
    <ul>
        <!INDIETRO>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'public',
                                        'action'     => 'reservedarea',
                                        ), 
                                        'default',true);?>" title="Torna alla home di area riservata">Indietro	</a></p>
        </li>
        <!Aggiungi FAQ>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'newfaq',
                                        ), 
                                        'default',true);?>" title="Aggiungi una nuova FAQ">Aggiungi FAQ	</a></p>
        </li>
        <!Elimina FAQ>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'deletefaq',
                                        ), 
                                        'default',true);?>" title="Elimina una FAQ">Elimina FAQ	</a></p>
        </li>

        <!Modifica FAQ>
        <li>
            <p class="p_menu"><a href="<?= $this->url(array(
                                        'controller' => 'admin',
                                        'action'     => 'updatefaq',
                                        ), 
                                        'default',true);?>" title="Modifica una FAQ">Modifica FAQ	</a></p>
        </li>


    </ul>
</div>